### ISSUE TITLE
Data acquisition

### ISSUE THREAD

**Issue by DavidLeDuy** [HSE-AAI-TeamOne/CarPricePredictor#6]
#5 Daten für ein genaueres Modell sammeln

**Comment by MGYG** [comment]
Neues Dataset auf Basis von Googel Bildern erstellt. Enthält alle 927 Modelle basierend auf der Preisdatenliste. Verunreinigte Bilder (Innenraum, Balken, Schriftzüge) sind teilweise vorhanden.

**Comment by DavidLeDuy** [comment]
Issue "vorerst" geschlossen
